apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-binding
  namespace: apache

subjects:
- kind: ServiceAccount
  name: developer
  namespace: apache

roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
